#!/usr/bin/env python3
"""Generate config.js from a business config JSON file.

Converts any named .json config into the fixed output file:
    any-name.json  ->  config.js   (window.__HUSTEL_CONFIG__)

The output name is always "config.js" so the pages' script tag and
script.js never need updating when you switch clients. The source can
live anywhere and be called anything:

Usage:
    python3 gen_data_js.py                        # uses ./config.json
    python3 gen_data_js.py configs/gyms/duna.json # -> ./config.js

Optionally pass --out to change where config.js is written:
    python3 gen_data_js.py configs/duna.json --out dist/config.js
"""
import json
import pathlib
import sys

HEADER = (
    "/* AUTO-GENERATED by gen_data_js.py from {src} — edit that file, "
    "then rerun the script */\n"
)


def generate(config_path: pathlib.Path, out_path: pathlib.Path) -> None:
    if not config_path.exists():
        raise SystemExit(f"not found: {config_path}")
    if config_path.suffix.lower() != ".json":
        raise SystemExit(f"expected a .json file, got: {config_path}")

    data = json.loads(config_path.read_text())
    out_path.write_text(
        HEADER.format(src=config_path)
        + "window.__HUSTEL_CONFIG__ = "
        + json.dumps(data, ensure_ascii=False, indent=2)
        + ";\n"
    )


def main():
    args = sys.argv[1:]
    out_path = pathlib.Path("config.js")
    if "--out" in args:
        i = args.index("--out")
        out_path = pathlib.Path(args[i + 1])
        del args[i:i + 2]
    targets = [pathlib.Path(a) for a in args] or [pathlib.Path("config.json")]

    if len(targets) > 1:
        raise SystemExit("only one config file per run — the output is always config.js")
    generate(targets[0], out_path)
    print(f"{targets[0]}  ->  {out_path}")


if __name__ == "__main__":
    main()

