/* AUTO-GENERATED by gen_data_js.py from config.json — edit that file, then rerun the script */
window.__HUSTEL_CONFIG__ = {
  "business_name": "Café Koraaa",
  "logo_url": "assets/logo.png",
  "tagline": "Le meilleur café du quartier, torréfié avec amour",
  "hero_subtitle": "Café de spécialité, pâtisseries maison et grains sélectionnés — au cœur de Casablanca.",
  "hero_image": "assets/hero.jpg",
  "meta_description": "Café Kora à Casablanca : café de spécialité, pâtisseries maison et grains sélectionnés. Venez nous voir Boulevard d'Anfa.",
  "primary_action": "visit",
  "phone": "+225 07 00 00 00 00",
  "whatsapp": "2250700000000",
  "whatsapp_link": "https://wa.me/2250700000000?text=Bonjour%20Caf%C3%A9%20Kora%2C%20je%20souhaite%20commander",
  "delivery_link": "https://glovoapp.com/example-link",
  "address": "Boulevard d'Anfa",
  "city": "Casablanca",
  "directions_link": "https://www.google.com/maps/dir/?api=1&destination=Caf%C3%A9+Kora+Boulevard+d%27Anfa+Casablanca",
  "google_maps_embed": "https://www.google.com/maps/embed?pb=Casablanca_Boulevard_Anfa_EXAMPLE",
  "instagram_url": "https://instagram.com/cafekora",
  "facebook_url": "https://facebook.com/cafekora",
  "currency": "MAD",
  "rating_average": "4.8",
  "review_count": "212",
  "gallery_note": "tout est fait maison, chaque jour.",
  "hours": {
    "0": [
      [
        "08:00",
        "20:00"
      ]
    ],
    "1": [
      [
        "07:30",
        "22:00"
      ]
    ],
    "2": [
      [
        "07:30",
        "22:00"
      ]
    ],
    "3": [
      [
        "07:30",
        "22:00"
      ]
    ],
    "4": [
      [
        "07:30",
        "22:00"
      ]
    ],
    "5": [
      [
        "07:30",
        "23:00"
      ]
    ],
    "6": [
      [
        "08:00",
        "23:00"
      ]
    ]
  },
  "features": [
    {
      "icon": "wifi",
      "title": "Wi-Fi rapide gratuit",
      "description": "Fibre optique — idéal pour travailler ou streamer.",
      "stat": "300 Mb/s"
    },
    {
      "icon": "snow",
      "title": "Climatisation",
      "description": "Un intérieur frais et confortable toute l'année.",
      "stat": "22°C"
    },
    {
      "icon": "leaf",
      "title": "Vue verte & terrasse",
      "description": "Détendez-vous face aux arbres, en intérieur comme en extérieur.",
      "stat": "24 places"
    },
    {
      "icon": "plug",
      "title": "Prises à chaque table",
      "description": "Branchez votre laptop, restez aussi longtemps que vous voulez.",
      "stat": "+30 prises"
    },
    {
      "icon": "headphones",
      "title": "Ambiance calme",
      "description": "Musique douce, coin lecture — parfait pour se concentrer.",
      "stat": "55 dB max"
    },
    {
      "icon": "coffee",
      "title": "Torréfaction de spécialité",
      "description": "Des grains sélectionnés et torréfiés localement.",
      "stat": "100% Arabica"
    }
  ],
  "menu_items": [
    {
      "name": "Café Espresso",
      "description": "Double shot, grains torréfiés localement.",
      "price": "25 MAD",
      "image": "assets/menu/espresso.jpg",
      "category": "Boissons"
    },
    {
      "name": "Cappuccino",
      "description": "Espresso, lait vapeur onctueux, cacao.",
      "price": "32 MAD",
      "image": "assets/menu/cappuccino.jpg",
      "category": "Boissons"
    },
    {
      "name": "Jus Frais du Jour",
      "description": "Fruits de saison pressés à la commande.",
      "price": "35 MAD",
      "image": "assets/menu/jus.jpg",
      "category": "Boissons"
    },
    {
      "name": "Fondant au Chocolat",
      "description": "Cœur coulant, glace vanille artisanale.",
      "price": "38 MAD",
      "image": "assets/menu/fondant.jpg",
      "category": "Pâtisseries"
    },
    {
      "name": "Cheesecake Fruits Rouges",
      "description": "Préparé chaque matin sur place.",
      "price": "42 MAD",
      "image": "assets/menu/cheesecake.jpg",
      "category": "Pâtisseries"
    }
  ],
  "gallery": [
    {
      "src": "assets/gallery/plat-signature.jpg",
      "alt": "Café Kora — plat signature"
    },
    {
      "src": "assets/gallery/latte-art.jpg",
      "alt": "Café Kora — café latte art"
    },
    {
      "src": "assets/gallery/interieur.jpg",
      "alt": "Café Kora — intérieur et ambiance"
    },
    {
      "src": "assets/gallery/dessert.jpg",
      "alt": "Café Kora — dessert maison"
    },
    {
      "src": "assets/gallery/terrasse.jpg",
      "alt": "Café Kora — terrasse"
    },
    {
      "src": "assets/gallery/barista.jpg",
      "alt": "Café Kora — barista au travail"
    }
  ],
  "testimonials": [
    {
      "author": "Aïcha M.",
      "source": "Google",
      "rating": 5,
      "text": "Le meilleur cappuccino du quartier, sans exagérer. L'ambiance est parfaite pour travailler ou se détendre."
    },
    {
      "author": "Karim D.",
      "source": "Instagram",
      "rating": 5,
      "text": "Brunch excellent et service très chaleureux. J'ai commandé via WhatsApp, tout était prêt à l'heure."
    },
    {
      "author": "Fatou S.",
      "source": "Google",
      "rating": 4,
      "text": "Cadre magnifique, desserts faits maison vraiment réussis. On revient chaque week-end en famille."
    }
  ],
  "theme": {
    "colors": {
      "primary": "#241a11",
      "primary_dark": "#1b130c",
      "accent": "#d0662f",
      "accent_soft": "#f3d9bd",
      "bg": "#faf4ea",
      "surface": "#fffdf8",
      "text": "#241a11",
      "text_muted": "#7d6d5c",
      "border": "#e8dcc9",
      "open": "#2e7d32",
      "closed": "#c62828",
      "dark_section": "#20170f"
    },
    "fonts": {
      "heading": "Fraunces",
      "body": "Outfit"
    },
    "radius": "18px"
  }
};
